# Generated by Django 6.1.1 on 2026-09-20 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Full name of the student.', max_length=100)),
                ('roll_number', models.CharField(help_text='Unique roll number for the student.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Roll number can only contain letters, numbers and hyphens.', regex='^[A-Za-z0-9\\-]+$')])),
                ('email', models.EmailField(help_text='A valid email address.', max_length=150)),
                ('phone', models.CharField(help_text='Contact phone number.', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optional leading +).', regex='^\\+?\\d{7,15}$')])),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('BSc Computer Science', 'BSc Computer Science'), ('BTech CSE', 'BTech CSE'), ('MCA', 'MCA'), ('MSc Computer Science', 'MSc Computer Science'), ('MBA', 'MBA'), ('Other', 'Other')], default='BCA', max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
                ('address', models.TextField(help_text='Residential address of the student.')),
                ('profile_photo', models.ImageField(blank=True, help_text='Upload a profile photo (optional).', null=True, upload_to='student_photos/')),
                ('joining_date', models.DateField(help_text='Date the student joined the institute.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
